audit_header: false
title: "Tampa Bay's Best Real Estate Training"
description: -- CLIENT NAME --, top Real Estate Agents in -- MARKET --, share their own internal real estate agent training for free. Their Real Estate Training, Tips and Advice will help you sell more homes in less time.
show_custom_links: true
custom_links:
  - title: Our Team
    url: http://www.theduncanduo.com/custompages_reports/About.htm
  - title: Career Night
    url: /career-night/
  - title: Radio Show
    url: https://soundcloud.com/theduncanduo/sets/tampa-real-estate
  - title: Videos
    url: /videos/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/006.jpg
    CTA_title: Come To Our Career Night
    CTA_text: The second Tuesday of every month, we'll be hosting a career night at our office starting at 6pm. Please fill out this form to register!
    CTA_link_text: Career Night
    CTA_url: /careers/


client:
  name: The Duncan Duo
  title:
  license_number:
  about_markdown: |
    If you are looking to start or jumpstart a real estate career, look no further than the Duncan Duo. They have been the #1 Realtors in Tampa Bay for several years running, are the #1 RE/MAX Agents in Florida, #6 in the World, and are the Official Real Estate Agents of The Tampa Bay Lightning. As one of the most respected Realtors in the country, The Duncan Duo have also garnered celebrity endorsements from Barbara Corcoran, Jack Harris, Sean Hannity, Glenn Beck, Ron Diaz and Dave McKay and you can hear their radio show every Sunday at 10am on 970WFLA. In addition, this year they ranked #561 on the Inc5000 list for America’s Fastest Growing Privately owned companies, their 2nd year on the list.

    They have a track record of doubling, tripling and quadrupling agent income from their prior Brokerages and have an amazing training and mentoring program for brand new agents to learn the business and get into production quickly. The Duo are regularly looking for great team members to join their team and you can inquire in the message box at the top or by <a href="http://tampa.craigslist.org/search/jjj?query=duncan+duo" target="_blank">clicking here to apply directly via our recent hiring ads</a>.
  market: Tampa Bay
  brand: The Duncan Duo & Associates
  brokerage: RE/MAX Dynamic
  address: 6320 S Dale Mabry Hwy<br>Tampa, Florida 33611
  phone: 813-359-8990
  phone_type:
  address2: 7430 N Tamiami Trail<br>Sarasota, FL 34243
  phone2: 941-888-4730
  phone2_type:
  email: careers@theduncanduo.com
  url: https://www.TheDuncanDuo.com

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/remaxdynamictampa/
  linkedin_url: https://www.linkedin.com/in/duncanduo?trk=hp-identity-name
  gplus_url: http://plus.google.com/+Theduncanduoremax/about
  youtube_url: http://www.youtube.com/user/TheDuncanDuo
  twitter_url: http://www.twitter.com/TheDuncanDuo
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url: https://itunes.apple.com/us/podcast/tampa-bay-real-estate-careers/id1177061984?mt=2

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  logo1: /img/logo1.png
  logo2: /img/logo2.png
  logo3: /img/logo3.png
  logo4: /img/logo4.png
  logo_width_number: 40
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#be0000'
  theme_color: '#0100c0'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
